// Root layout — wraps every page in the app.
// Applies global fonts and sets page-level metadata.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load the Geist sans-serif font and expose it as a CSS variable for Tailwind
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load the Geist monospace font for code blocks and the editor
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default metadata shown in the browser tab and search engine results
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Set the document language for screen readers and search engines
    <html lang="en">
      <body
        // Apply both font CSS variables and enable font antialiasing globally
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Browser extensions (dark mode, Grammarly, etc.) inject attributes onto
        // <body> before React loads — suppress the resulting hydration mismatch
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
